version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - store-network

networks:
  store-network:

volumes:
  mysql_data: