spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
